#!/usr/bin/env python3
"""Deterministic inputs for 08_mipmap_gen_chain.
Each record: width, maxLevel, then width*width signed ARGB ints (the base texture, row-major).
Levels 1..maxLevel are generated by the kernel (never supplied).

Uses square power-of-two textures so j = width>>level stays positive for all levels.
Includes some textures with fully-transparent pixels among the first (maxLevel+1) base pixels so
the transparency-flag branch (whose loop bound is maxLevel+1, verbatim) fires for some records.
"""
import random

WIDTH = 16
MAX_LEVEL = 4
N_TEX = 180  # 180 * (256+64+16+4+1) = 61380 output lines


def rand_argb(rnd, allow_transparent):
    if allow_transparent and rnd.random() < 0.25:
        a = 0
    else:
        a = rnd.randint(0, 255)
    r = rnd.randint(0, 255)
    g = rnd.randint(0, 255)
    b = rnd.randint(0, 255)
    val = (a << 24) | (r << 16) | (g << 8) | b
    if val >= 0x80000000:
        val -= 0x100000000
    return val


def main():
    rnd = random.Random(808)
    n = WIDTH * WIDTH
    out = []
    for t in range(N_TEX):
        # half the textures may contain transparent pixels (flag can flip on per first 5 pixels)
        allow_t = (t % 2 == 0)
        out.append(f"{WIDTH} {MAX_LEVEL}")
        for _ in range(n):
            out.append(str(rand_argb(rnd, allow_t)))
    print("\n".join(out))


if __name__ == "__main__":
    main()
