#!/usr/bin/env bash
# agent_worktree.sh NAME [BASE] - isolated worktree for a delegated agent.
#
# A bare `git worktree add` gives an agent a tree that cannot build and cannot
# replay: every heavy input here is gitignored. Two failure modes we have
# already paid for:
#   - verify/tapes/* is ignored wholesale, so the worktree has
#     no tapes at all; a missing <tape>_world sidecar makes replay_tape.py skip
#     snapshot patching SILENTLY and the agent reports a clean gate on a world
#     that never got patched.
#   - magma/assets/*.h are generated by bootstrap_assets.sh; without them the
#     build fails outright.
# Both are linked in here, so the worktree behaves like the main tree.
#
#   bash scripts/agent_worktree.sh leafcut          # -> $HOME/dev/nw/leafcut
#   bash scripts/agent_worktree.sh leafcut HEAD~3
set -euo pipefail

NAME=${1:?usage: agent_worktree.sh NAME [BASE]}
BASE=${2:-HEAD}
ROOT=$(git rev-parse --show-toplevel)
WT="$HOME/dev/nw/$NAME"

[ -e "$WT" ] && { echo "exists: $WT" >&2; exit 1; }
git -C "$ROOT" worktree add -b "wt/$NAME" "$WT" "$BASE" >/dev/null
echo "worktree $WT on wt/$NAME from $(git -C "$ROOT" rev-parse --short "$BASE")"

# Every tapes/ entry, including the *_world snapshot dirs and .snapshot_patch
# sidecars. Link, never copy: these are gigabytes.
mkdir -p "$WT/verify/tapes"
n=0
for e in "$ROOT"/verify/tapes/*; do
    [ -e "$e" ] || continue
    t="$WT/verify/tapes/$(basename "$e")"
    [ -e "$t" ] && continue
    ln -s "$e" "$t"; n=$((n+1))
done
echo "linked $n tapes/ entries"

# Generated asset headers (bootstrap_assets.sh output).
a=0
# COPY (not symlink): make's regeneration rules stat these against sources
# and a symlink's target mtime makes it try to rebuild them, which fails
# without a jar in the worktree (found by the blazeglow agent 2026-07-29).
for e in "$ROOT"/magma/assets/*.h; do
    [ -e "$e" ] || continue
    t="$WT/magma/assets/$(basename "$e")"
    [ -e "$t" ] && continue
    cp "$e" "$t"; a=$((a+1))
done
# Fresh mtimes: a header older than a recently edited assets/build_*.py makes
# make regenerate it, which fails without a jar in the worktree.
touch "$WT"/magma/assets/*.h 2>/dev/null || true
echo "linked $a generated asset headers"

# Oracle goldens / captures used by the non-tape gates.
for d in verify/mc_capture/goldens \
         verify/ui_hud/goldens \
         verify/ui_entities/goldens; do
    [ -d "$ROOT/$d" ] || continue
    [ -e "$WT/$d" ] && continue
    mkdir -p "$(dirname "$WT/$d")"; ln -s "$ROOT/$d" "$WT/$d"; echo "linked $d"
done

echo
echo "REMINDER: tracked-file edits in $ROOT do NOT reach this worktree."
echo "Rebase or cherry-pick before trusting a gate run here."
