#!/bin/bash
# Export a clean-history public tree of this repo: every tracked file EXCEPT
# Mojang-derived content (decompiled source, texture-derived generated
# headers, real-game captures/renders). The excluded classes are all
# regenerated locally from the user's own Minecraft installation by
# scripts/bootstrap_oracle.sh + scripts/bootstrap_assets.sh, byte-identical.
#
# Usage: bash scripts/export_public_tree.sh /path/to/netherite-public
# The destination gets a fresh `git init` (NEVER reuse this repo's history -
# it contains the excluded content in past commits).
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
DST="${1:?usage: export_public_tree.sh <dest-dir>}"
cd "$REPO"

list=$(mktemp)
# tracked files that still exist in the working tree
git ls-files -z | while IFS= read -r -d '' f; do
    if [ -e "$f" ]; then printf '%s\n' "$f"; fi
done > "$list"

# ---- exclusions: Mojang-derived, regenerated by the bootstrap scripts ----
filtered=$(mktemp)
# re-include SAFE media: pure palette renders of the semantic camera,
# zero Mojang-derived pixels (built by scripts/batch_obs_record.py)
ALLOW='^docs/assets/zoom_farm\.gif$'
grep -vE \
    -e '^java/oracle-src/' \
    -e '^magma/assets/(atlas_gen|colormap_gen|gui_atlas|hand_atlas|hud_atlas|inventory_ui_atlas|item_atlas|loading_bg|mob_atlas|portal_tex|sky_atlas|underwater_tex|water_frames)\.h$' \
    -e '\.(png|ppm|jpg|jpeg|gif|mp4)$' \
    "$list" > "$filtered"
grep -E "$ALLOW" "$list" >> "$filtered" || true

mkdir -p "$DST"
rsync -a --files-from="$filtered" "$REPO/" "$DST/"

# gitignore the regenerated paths in the public tree
cat >> "$DST/.gitignore" <<'EOF'

# ---- regenerated from YOUR Minecraft install (never committed) ----
# scripts/bootstrap_oracle.sh
java/oracle-src/
# scripts/bootstrap_assets.sh
magma/assets/atlas_gen.h
magma/assets/colormap_gen.h
magma/assets/gui_atlas.h
magma/assets/hand_atlas.h
magma/assets/inventory_ui_atlas.h
magma/assets/hud_atlas.h
magma/assets/item_atlas.h
magma/assets/loading_bg.h
magma/assets/mob_atlas.h
magma/assets/portal_tex.h
magma/assets/sky_atlas.h
magma/assets/underwater_tex.h
magma/assets/water_frames.h
EOF

n_all=$(wc -l < "$list"); n_pub=$(wc -l < "$filtered")
echo "exported $n_pub/$n_all tracked files -> $DST"
echo "excluded $((n_all - n_pub)) Mojang-derived files (bootstrap regenerates them)"
rm -f "$list" "$filtered"
