#!/usr/bin/env python3
"""Extract inventory-only UI sprites from the MC 1.11.2 client jar.

This stays separate from gui_atlas.h so regenerating the armor/offhand empty-slot
sprites cannot renumber or otherwise modify the GUI item-icon mapping.
"""
import io
import os
import zipfile

from PIL import Image

from mc_jar import find_jar


JAR = find_jar()
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "inventory_ui_atlas.h")
TEX = "assets/minecraft/textures/items/"
SPRITES = (
    ("EMPTY_HELMET", "empty_armor_slot_helmet.png"),
    ("EMPTY_CHESTPLATE", "empty_armor_slot_chestplate.png"),
    ("EMPTY_LEGGINGS", "empty_armor_slot_leggings.png"),
    ("EMPTY_BOOTS", "empty_armor_slot_boots.png"),
    ("EMPTY_SHIELD", "empty_armor_slot_shield.png"),
)


def main():
    with zipfile.ZipFile(JAR) as zf:
        images = []
        for symbol, member in SPRITES:
            image = Image.open(io.BytesIO(zf.read(TEX + member))).convert("RGBA")
            if image.size != (16, 16):
                raise SystemExit(f"{member}: expected 16x16, got {image.size}")
            images.append((symbol, image.tobytes()))

    with open(OUT_H, "w") as out:
        out.write("/* GENERATED by assets/build_inventory_ui_atlas.py. */\n")
        out.write("#ifndef MAGMA_INVENTORY_UI_ATLAS_H\n")
        out.write("#define MAGMA_INVENTORY_UI_ATLAS_H\n\n")
        out.write("#define INVENTORY_UI_SPRITE_COUNT 5\n")
        for index, (symbol, _) in enumerate(images):
            out.write(f"#define INVENTORY_UI_{symbol} {index}\n")
        out.write("\nstatic const unsigned char INVENTORY_UI_RGBA[5][16 * 16 * 4] = {\n")
        for symbol, pixels in images:
            out.write(f"    {{ /* {symbol} */\n")
            for i in range(0, len(pixels), 16):
                out.write("        " + ",".join(str(v) for v in pixels[i:i + 16]) + ",\n")
            out.write("    },\n")
        out.write("};\n\n#endif /* MAGMA_INVENTORY_UI_ATLAS_H */\n")

    print(f"wrote {OUT_H}: {len(images)} inventory UI sprites")


if __name__ == "__main__":
    main()
