#!/usr/bin/env python3
"""Convert Mojang's MC 1.11.2 End City NBT templates to a compact C header.

Run: uv run --no-project --with nbtlib python assets/build_end_city_templates.py

The generated data contains every template cell (including air, required by
the OVERWRITE placement setting) and every DATA marker. Runtime code performs
Minecraft's rotation and recursive piece assembly.
"""
import gzip
import io
import os
import zipfile

import nbtlib

from mc_jar import find_jar


JAR = find_jar()
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "end_city_templates.h")
PREFIX = "assets/minecraft/structures/endcity/"


FACING_META = {
    "down": 0, "up": 1, "north": 2, "south": 3, "west": 4, "east": 5,
}


def legacy_state(entry):
    name = str(entry["Name"])
    prop = {str(k): str(v) for k, v in entry.get("Properties", {}).items()}
    if name == "minecraft:air":
        return 0, 0
    if name == "minecraft:purpur_block":
        return 201, 0
    if name == "minecraft:purpur_pillar":
        return 202, {"y": 0, "x": 4, "z": 8}[prop["axis"]]
    if name == "minecraft:purpur_stairs":
        # BlockStairs: SOUTH=0, WEST=1, NORTH=2, EAST=3; top bit is 4.
        meta = {"south": 0, "west": 1, "north": 2, "east": 3}[prop["facing"]]
        return 203, meta | (4 if prop["half"] == "top" else 0)
    if name == "minecraft:purpur_slab":
        return 205, 8 if prop["half"] == "top" else 0
    if name == "minecraft:end_bricks":
        return 206, 0
    if name == "minecraft:structure_block":
        return 255, 0
    if name == "minecraft:stained_glass":
        assert prop["color"] == "magenta"
        return 95, 2
    if name == "minecraft:end_rod":
        return 198, FACING_META[prop["facing"]]
    if name == "minecraft:chest":
        return 54, FACING_META[prop["facing"]]
    if name == "minecraft:obsidian":
        return 49, 0
    if name == "minecraft:skull":
        return 144, FACING_META[prop["facing"]]
    if name == "minecraft:brewing_stand":
        meta = sum((1 << i) for i in range(3)
                   if prop.get("has_bottle_%d" % i) == "true")
        return 117, meta
    if name == "minecraft:ladder":
        return 65, FACING_META[prop["facing"]]
    if name == "minecraft:ender_chest":
        return 130, FACING_META[prop["facing"]]
    if name == "minecraft:wall_banner":
        return 177, FACING_META[prop["facing"]]
    raise ValueError("unmapped End City state: %r %r" % (name, prop))


def main():
    templates = []
    with zipfile.ZipFile(JAR) as jar:
        names = sorted(n for n in jar.namelist()
                       if n.startswith(PREFIX) and n.endswith(".nbt"))
        if len(names) != 21:
            raise SystemExit("expected 21 End City templates, found %d" % len(names))
        for member in names:
            root = nbtlib.File.parse(io.BytesIO(gzip.decompress(jar.read(member))))
            palette = [legacy_state(state) for state in root["palette"]]
            blocks = []
            markers = []
            for block in root["blocks"]:
                x, y, z = map(int, block["pos"])
                block_id, meta = palette[int(block["state"])]
                if block_id != 255:
                    blocks.append((x, y, z, block_id, meta))
                tag = block.get("nbt")
                if tag is not None and str(tag.get("mode", "")) == "DATA":
                    kind = {"Chest": 1, "Sentry": 2, "Elytra": 3}.get(
                        str(tag.get("metadata", "")), 0)
                    if kind:
                        markers.append((x, y, z, kind))
            template_name = member[len(PREFIX):-4]
            templates.append((template_name, tuple(map(int, root["size"])),
                              blocks, markers))

    with open(OUT_H, "w") as out:
        out.write("/* GENERATED by assets/build_end_city_templates.py. */\n")
        out.write("#ifndef MAGMA_END_CITY_TEMPLATES_H\n")
        out.write("#define MAGMA_END_CITY_TEMPLATES_H\n\n")
        out.write("typedef struct { unsigned char x,y,z,id,meta; } GmEcBlock;\n")
        out.write("typedef struct { unsigned char x,y,z,kind; } GmEcMarker;\n")
        out.write("typedef struct { const char *name; unsigned char sx,sy,sz; "
                  "const GmEcBlock *blocks; unsigned short block_count; "
                  "const GmEcMarker *markers; unsigned char marker_count; } "
                  "GmEcTemplate;\n\n")
        for index, (name, size, blocks, markers) in enumerate(templates):
            out.write("static const GmEcBlock GM_EC_BLOCKS_%d[%d] = {\n" %
                      (index, len(blocks)))
            for x, y, z, block_id, meta in blocks:
                out.write("{%d,%d,%d,%d,%d}," % (x, y, z, block_id, meta))
            out.write("\n};\n")
            if markers:
                out.write("static const GmEcMarker GM_EC_MARKERS_%d[%d] = {" %
                          (index, len(markers)))
                for x, y, z, kind in markers:
                    out.write("{%d,%d,%d,%d}," % (x, y, z, kind))
                out.write("};\n")
        out.write("\n#define GM_EC_TEMPLATE_COUNT %d\n" % len(templates))
        out.write("static const GmEcTemplate GM_EC_TEMPLATES[GM_EC_TEMPLATE_COUNT] = {\n")
        for index, (name, size, blocks, markers) in enumerate(templates):
            marker_ref = "GM_EC_MARKERS_%d" % index if markers else "0"
            out.write('{"%s",%d,%d,%d,GM_EC_BLOCKS_%d,%d,%s,%d},\n' %
                      (name, size[0], size[1], size[2], index, len(blocks),
                       marker_ref, len(markers)))
        out.write("};\n\n#endif\n")
    print("end city templates: %d templates, %d blocks, %d markers" % (
        len(templates), sum(len(t[2]) for t in templates),
        sum(len(t[3]) for t in templates)))
    print("wrote:", OUT_H)


if __name__ == "__main__":
    main()
