#!/usr/bin/env python3
"""Extract the default player skins (steve.png + alex.png) into assets/hand_atlas.h.

Run: uv run --no-project --with pillow python assets/build_hand_atlas.py

The first-person HAND (game/hand.c) is the default-skin RIGHT ARM box, textured
with the vanilla 64x64 skin. Rather than pre-crop the arm sub-rect, we emit the
WHOLE skin as one RGBA image so game/hand.c can address any face rect it needs
by [0,1] uv; the arm faces are a known sub-region of it (see hand.c ARM_QUADS).
Both default variants are emitted: steve (4px "default" arm, texU=40,texV=16 of
a 4x12x4 unwrap) and alex (3px "slim" arm, 3x12x4 unwrap at the same origin) -
offline players get either by UUID hash, so replay selects per tape. Byte order
per texel is R,G,B,A (matches CrRgba). Also dumps /tmp/magma_{steve,alex}.png.
"""
import os
import tempfile
import zipfile

from PIL import Image

from mc_jar import find_jar  # noqa: E402
JAR = find_jar()
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "hand_atlas.h")
SKINS = ("steve", "alex")


def load_skin(name):
    skin = "assets/minecraft/textures/entity/%s.png" % name
    with tempfile.TemporaryDirectory() as tmpdir:
        with zipfile.ZipFile(JAR) as zf:
            zf.extract(skin, tmpdir)
            img = Image.open(os.path.join(tmpdir, skin)).convert("RGBA")
    # Modern skins are 64x64; legacy 64x32 lack the second-layer arm rows but the
    # base arm rect (40,16..) is present in both. Normalize to 64x64 (pad bottom).
    if img.size != (64, 64):
        canvas = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
        canvas.paste(img, (0, 0))
        img = canvas
    img.save("/tmp/magma_%s.png" % name)
    px = img.tobytes()  # RGBA row-major, len = 64*64*4
    assert len(px) == 64 * 64 * 4
    return px


def main():
    if not os.path.exists(JAR):
        raise SystemExit("jar not found: " + JAR)

    with open(OUT_H, "w") as f:
        f.write("/* GENERATED by assets/build_hand_atlas.py - DO NOT EDIT.\n")
        f.write(" * Default MC 1.11.2 player skins (steve.png / alex.png), 64x64 RGBA.\n")
        f.write(" * Byte order per texel: R,G,B,A (matches CrRgba memory layout).\n")
        f.write(" * game/hand.c textures the first-person right-arm box from the\n")
        f.write(" * arm sub-rect at texU=40,texV=16 (steve: 4x12x4 unwrap; alex\n")
        f.write(" * \"slim\": 3x12x4 unwrap - see hand.c ARM_QUADS/ARM_QUADS_SLIM). */\n")
        f.write("#ifndef MAGMA_HAND_ATLAS_H\n#define MAGMA_HAND_ATLAS_H\n\n")
        f.write("#define HAND_SKIN_W 64\n")
        f.write("#define HAND_SKIN_H 64\n\n")
        for name in SKINS:
            px = load_skin(name)
            f.write("static const unsigned char HAND_SKIN_RGBA_%s[%d] = {\n"
                    % (name.upper(), len(px)))
            for i in range(0, len(px), 16):
                chunk = px[i:i + 16]
                f.write("    " + ",".join("%d" % b for b in chunk) + ",\n")
            f.write("};\n\n")
        f.write("/* legacy alias: the non-slim default skin */\n")
        f.write("#define HAND_SKIN_RGBA HAND_SKIN_RGBA_STEVE\n\n")
        f.write("#endif /* MAGMA_HAND_ATLAS_H */\n")

    print("wrote %s (steve + alex), dumped /tmp/magma_steve.png /tmp/magma_alex.png"
          % OUT_H)


if __name__ == "__main__":
    main()
