#!/usr/bin/env python3
"""Extract the real MC 1.11.2 grass/foliage biome colormaps to a C header.

Run: uv run --no-project --with pillow python assets/build_colormap.py

Unzips assets/minecraft/textures/colormap/{grass,foliage}.png (each 256x256) from
the client jar and emits assets/colormap_gen.h holding both as row-major
0xRRGGBB int tables of length 256*256.

Index convention matches Minecraft's ColorizerGrass/ColorizerFoliage exactly:
  buffer[j << 8 | i]  where  i = (int)((1-temperature)*255), j = (int)((1-humidity)*255)
TextureUtil.readImageData does BufferedImage.getRGB(0,0,w,h,aint,0,w), i.e.
aint[y*w + x] = ARGB(x,y); with w=256 that is exactly aint[y<<8 | x]. So the PNG
row-major pixel order (x=column=temperature-index i, y=row=humidity-index j) is
stored verbatim here. Do NOT edit build_atlas.py / atlas_gen.h (separate asset).
"""
import os
import tempfile
import zipfile

from PIL import Image

from mc_jar import find_jar  # noqa: E402
JAR = find_jar()
COLORMAP = "assets/minecraft/textures/colormap/"
DIM = 256
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "colormap_gen.h")


def load_colormap(zf, tmpdir, name):
    """Extract one 256x256 colormap PNG, return a list of 65536 0xRRGGBB ints
    in row-major (y*256 + x) order."""
    member = COLORMAP + name + ".png"
    zf.extract(member, tmpdir)
    img = Image.open(os.path.join(tmpdir, member)).convert("RGB")
    w, h = img.size
    if (w, h) != (DIM, DIM):
        raise SystemExit("unexpected colormap size %dx%d for %s" % (w, h, name))
    out = []
    for (r, g, b) in img.getdata():  # getdata() is row-major (y*w + x)
        out.append((r << 16) | (g << 8) | b)
    assert len(out) == DIM * DIM
    return out


def emit_table(f, cname, vals):
    f.write("static const unsigned int %s[%d] = {\n" % (cname, len(vals)))
    for i in range(0, len(vals), 12):
        chunk = vals[i:i + 12]
        f.write("    " + ",".join("0x%06X" % v for v in chunk) + ",\n")
    f.write("};\n\n")


def main():
    if not os.path.exists(JAR):
        raise SystemExit("jar not found: " + JAR)

    with tempfile.TemporaryDirectory() as tmpdir:
        with zipfile.ZipFile(JAR) as zf:
            grass = load_colormap(zf, tmpdir, "grass")
            foliage = load_colormap(zf, tmpdir, "foliage")

    with open(OUT_H, "w") as f:
        f.write("/* GENERATED by assets/build_colormap.py - DO NOT EDIT.\n")
        f.write(" * Real MC 1.11.2 biome colormaps (grass.png, foliage.png), 256x256.\n")
        f.write(" * Row-major 0xRRGGBB; index [j<<8 | i] exactly as ColorizerGrass/\n")
        f.write(" * ColorizerFoliage.getGrassColor/getFoliageColor do. */\n")
        f.write("#ifndef MAGMA_COLORMAP_GEN_H\n#define MAGMA_COLORMAP_GEN_H\n\n")
        f.write("#define CR_COLORMAP_DIM %d\n\n" % DIM)
        emit_table(f, "CR_GRASS_COLORMAP", grass)
        emit_table(f, "CR_FOLIAGE_COLORMAP", foliage)
        f.write("#endif /* MAGMA_COLORMAP_GEN_H */\n")

    print("colormap: 2x %dx%d, wrote %s" % (DIM, DIM, OUT_H))


if __name__ == "__main__":
    main()
