#!/usr/bin/env python3
"""Extract the vanilla 1.11.2 loading-screen background into a C header.

Run: uv run --no-project --with pillow python assets/build_loading_bg.py
"""

import io
import os
import zipfile

from PIL import Image

from mc_jar import find_jar  # noqa: E402
JAR = find_jar()
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "loading_bg.h")


def main():
    with zipfile.ZipFile(JAR) as archive:
        image = Image.open(
            io.BytesIO(
                archive.read("assets/minecraft/textures/gui/options_background.png")
            )
        ).convert("RGBA")
    if image.size != (16, 16):
        raise SystemExit(f"unexpected loading background size {image.size}")
    pixels = image.tobytes()
    with open(OUT_H, "w") as output:
        output.write(
            "/* GENERATED by assets/build_loading_bg.py - DO NOT EDIT. */\n"
            "#ifndef MAGMA_ASSETS_LOADING_BG_H\n"
            "#define MAGMA_ASSETS_LOADING_BG_H\n\n"
            "static const unsigned char CR_LOADING_BG_RGBA[1024] = {\n"
        )
        for offset in range(0, len(pixels), 16):
            output.write(
                "    "
                + ",".join(str(byte) for byte in pixels[offset : offset + 16])
                + ",\n"
            )
        output.write("};\n\n#endif /* MAGMA_ASSETS_LOADING_BG_H */\n")
    print(f"wrote {OUT_H} (16x16)")


if __name__ == "__main__":
    main()
