#!/usr/bin/env python3
"""Extract every vanilla 1.11.2 portal animation frame into a C header.

Run: uv run --no-project --with pillow python assets/build_portal.py
"""
import io
import os
import zipfile

from PIL import Image

from mc_jar import find_jar  # noqa: E402
JAR = find_jar()
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "portal_tex.h")


def main():
    with zipfile.ZipFile(JAR) as archive:
        image = Image.open(io.BytesIO(archive.read(
            "assets/minecraft/textures/blocks/portal.png"))).convert("RGBA")
    width, height = image.size
    if width != 16 or height % width:
        raise SystemExit(f"unexpected portal texture size {width}x{height}")
    frames = height // width
    with open(OUT_H, "w") as output:
        output.write("/* GENERATED by assets/build_portal.py - DO NOT EDIT.\n"
                     " * MC 1.11.2 blocks/portal.png animation frames. */\n"
                     "#ifndef MAGMA_ASSETS_PORTAL_TEX_H\n"
                     "#define MAGMA_ASSETS_PORTAL_TEX_H\n\n")
        output.write(f"#define CR_PORTAL_TEX_FRAMES {frames}\n"
                     f"#define CR_PORTAL_TEX_W {width}\n"
                     f"#define CR_PORTAL_TEX_H {width}\n\n")
        output.write("static const unsigned char "
                     "CR_PORTAL_TEX[CR_PORTAL_TEX_FRAMES][1024] = {\n")
        for frame in range(frames):
            pixels = image.crop((0, frame * width, width,
                                 (frame + 1) * width)).tobytes()
            output.write("  {\n")
            for offset in range(0, len(pixels), 16):
                output.write("    " + ",".join(
                    str(byte) for byte in pixels[offset:offset + 16]) + ",\n")
            output.write("  },\n")
        output.write("};\n\n#endif /* MAGMA_ASSETS_PORTAL_TEX_H */\n")
    print(f"wrote {OUT_H} ({frames} frames, {width}x{width})")


if __name__ == "__main__":
    main()
