#!/usr/bin/env python3
"""Build a generated C header of the REAL MC 1.11.2 SKY textures.

Run: uv run --no-project --with pillow python assets/build_sky_atlas.py

Mirrors build_atlas.py but for the celestial / atmosphere assets that
RenderGlobal.renderSky + renderClouds bind:
  - environment/sun.png          (32x32 RGB, the textured sun quad)
  - environment/moon_phases.png  (128x64, 4x2 grid of 32x32 phase cells;
                                  we emit the FULL-MOON cell = col0,row0)
  - environment/clouds.png       (256x256 RGBA cloud cells)
  - environment/end_sky.png      (128x128 repeating End cube texture)
  - environment/rain.png         (64x256 repeating precipitation texture)
  - environment/snow.png         (64x256 repeating precipitation texture)

Emits assets/sky_atlas.h with six RGBA byte arrays + dims. Byte order per
texel is R,G,B,A (matches CrRgba). Also dumps PNGs to /tmp for eyeballing.

Does NOT touch build_atlas.py / atlas_gen.h.
"""
import os
import tempfile
import zipfile

from PIL import Image

from mc_jar import find_jar  # noqa: E402
JAR = find_jar()
ENV = "assets/minecraft/textures/environment/"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "sky_atlas.h")


def extract(zf, tmpdir, name):
    member = ENV + name
    zf.extract(member, tmpdir)
    return Image.open(os.path.join(tmpdir, member)).convert("RGBA")


def emit_array(f, cname, wname, hname, img):
    w, h = img.size
    px = img.tobytes()  # RGBA row-major
    assert len(px) == w * h * 4
    f.write("#define %s %d\n" % (wname, w))
    f.write("#define %s %d\n\n" % (hname, h))
    f.write("static const unsigned char %s[%d] = {\n" % (cname, len(px)))
    for i in range(0, len(px), 20):
        chunk = px[i:i + 20]
        f.write("    " + ",".join("%d" % b for b in chunk) + ",\n")
    f.write("};\n\n")


def main():
    if not os.path.exists(JAR):
        raise SystemExit("jar not found: " + JAR)

    with tempfile.TemporaryDirectory() as tmpdir:
        with zipfile.ZipFile(JAR) as zf:
            sun = extract(zf, tmpdir, "sun.png")
            moon_strip = extract(zf, tmpdir, "moon_phases.png")
            clouds = extract(zf, tmpdir, "clouds.png")
            end_sky = extract(zf, tmpdir, "end_sky.png")
            rain = extract(zf, tmpdir, "rain.png")
            snow = extract(zf, tmpdir, "snow.png")

    # Full-moon cell: RenderGlobal uses phase i=0 -> k=i%4=0, i1=i/4%2=0, so the
    # texture cell is columns [0,1/4] x rows [0,1/2] = the top-left 32x32 tile.
    mw, mh = moon_strip.size            # 128 x 64
    cw, ch = mw // 4, mh // 2           # 32 x 32
    moon = moon_strip.crop((0, 0, cw, ch))

    sun.save("/tmp/magma_sun.png")
    moon.save("/tmp/magma_moon.png")
    clouds.save("/tmp/magma_clouds.png")
    end_sky.save("/tmp/magma_end_sky.png")
    rain.save("/tmp/magma_rain.png")
    snow.save("/tmp/magma_snow.png")

    with open(OUT_H, "w") as f:
        f.write("/* GENERATED by assets/build_sky_atlas.py - DO NOT EDIT.\n")
        f.write(" * Real MC 1.11.2 celestial/atmosphere textures (RGBA, R,G,B,A per texel).\n")
        f.write(" *   sun.png (32x32), moon_phases full-moon cell (32x32), clouds.png (256x256),\n")
        f.write(" *   end_sky.png (128x128 repeating End cube texture), rain.png and\n")
        f.write(" *   snow.png (64x256 repeating precipitation textures).\n")
        f.write(" * Consumed by game/sky.c and game/weather_render.h. */\n")
        f.write("#ifndef MAGMA_SKY_ATLAS_H\n#define MAGMA_SKY_ATLAS_H\n\n")
        emit_array(f, "CR_SUN_RGBA", "CR_SUN_W", "CR_SUN_H", sun)
        emit_array(f, "CR_MOON_RGBA", "CR_MOON_W", "CR_MOON_H", moon)
        emit_array(f, "CR_CLOUDS_RGBA", "CR_CLOUDS_W", "CR_CLOUDS_H", clouds)
        emit_array(f, "CR_END_SKY_RGBA", "CR_END_SKY_W", "CR_END_SKY_H", end_sky)
        emit_array(f, "CR_RAIN_RGBA", "CR_RAIN_W", "CR_RAIN_H", rain)
        emit_array(f, "CR_SNOW_RGBA", "CR_SNOW_W", "CR_SNOW_H", snow)
        f.write("#endif /* MAGMA_SKY_ATLAS_H */\n")

    print("sun %s  moon-cell %s  clouds %s  end-sky %s  rain %s  snow %s" %
          (sun.size, moon.size, clouds.size, end_sky.size, rain.size, snow.size))
    print("wrote %s" % OUT_H)
    print("dumped /tmp/magma_sun.png /tmp/magma_moon.png /tmp/magma_clouds.png "
          "/tmp/magma_end_sky.png /tmp/magma_rain.png /tmp/magma_snow.png")


if __name__ == "__main__":
    main()
