#!/usr/bin/env python3
"""Extract textures/misc/underwater.png (the first-person eye-in-water screen
overlay, ItemRenderer.renderWaterOverlayTexture) into a generated C header.

Run: uv run --no-project --with pillow python assets/build_underwater.py
"""
import io
import os
import zipfile

from PIL import Image

from mc_jar import find_jar  # noqa: E402
JAR = find_jar()
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "underwater_tex.h")


def main():
    with zipfile.ZipFile(JAR) as z:
        im = Image.open(io.BytesIO(
            z.read("assets/minecraft/textures/misc/underwater.png"))).convert("RGBA")
    w, h = im.size
    px = im.tobytes()
    with open(OUT_H, "w") as f:
        f.write("/* GENERATED by assets/build_underwater.py - DO NOT EDIT.\n"
                " * MC 1.11.2 textures/misc/underwater.png, RGBA row-major. */\n")
        f.write("#ifndef MAGMA_ASSETS_UNDERWATER_TEX_H\n"
                "#define MAGMA_ASSETS_UNDERWATER_TEX_H\n\n")
        f.write(f"#define CR_UNDERWATER_TEX_W {w}\n#define CR_UNDERWATER_TEX_H {h}\n\n")
        f.write("static const unsigned char CR_UNDERWATER_TEX[] = {\n")
        for i in range(0, len(px), 16):
            f.write("    " + ",".join(str(b) for b in px[i:i + 16]) + ",\n")
        f.write("};\n\n#endif /* MAGMA_ASSETS_UNDERWATER_TEX_H */\n")
    print(f"wrote {OUT_H} ({w}x{h})")


if __name__ == "__main__":
    main()
